### ISSUE TITLE
free command should show what's free and not what's taken

### ISSUE THREAD

**Issue by richardhartme** [Hates/envbot-crystal#1]
Bit confusing that the `free` command shows what's taken. Should show what's actually free. This would mean providing a list of environments.

**Comment by lsigism** [comment]
Maybe you could change the command to accept only the text "free POs" or something like that, then when someone sends a message with word "free" on it the slackbot won't display the free environments.

**Comment by Hates** [comment]
Fixed 👍

**Comment by richardhartme** [comment]
Fixed 👍
